### ISSUE TITLE
Stakeholder analysis

### ISSUE THREAD

**Issue by lbelmore** [hc-sc/rsa-renewal#24]
Validate processes within the programs and complete the stakeholder analysis section of the BRD

**Comment by lbelmore** [comment]
First round of validation was done with Nick and the CPS team last week. Need to send the revised SIPOC for confirmation asap.

**Comment by bdelima1311** [comment]
The revised SIPOC-SWIMMING Lane diagram was completed on February 25, 2019; it was sent to Louis Michaud and Lisa Belmore via email.  This task was completed within the timeline established with no negative variance.

**Comment by lbelmore** [comment]
Thanks Ben! I have sent it off to Nick and his team for final validation!
